# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sample_data.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='sample_data.proto',
  package='',
  syntax='proto2',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x11sample_data.proto\"\xbf\x01\n\nSampleData\x12\x13\n\x0b\x43ustomer_ID\x18\x01 \x01(\x03\x12 \n\x18\x43ustomer_Enrollment_Date\x18\x02 \x01(\x03\x12\x15\n\rCustomer_Name\x18\x03 \x01(\t\x12\x18\n\x10\x43ustomer_Address\x18\x04 \x01(\t\x12\x15\n\rCustomer_Tier\x18\x05 \x01(\t\x12\x1c\n\x14\x41\x63tive_Subscriptions\x18\x06 \x01(\t\x12\x14\n\x0c_CHANGE_TYPE\x18\x07 \x01(\t'
)




_SAMPLEDATA = _descriptor.Descriptor(
  name='SampleData',
  full_name='SampleData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='Customer_ID', full_name='SampleData.Customer_ID', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='Customer_Enrollment_Date', full_name='SampleData.Customer_Enrollment_Date', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='Customer_Name', full_name='SampleData.Customer_Name', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='Customer_Address', full_name='SampleData.Customer_Address', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='Customer_Tier', full_name='SampleData.Customer_Tier', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='Active_Subscriptions', full_name='SampleData.Active_Subscriptions', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='_CHANGE_TYPE', full_name='SampleData._CHANGE_TYPE', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=22,
  serialized_end=213,
)

DESCRIPTOR.message_types_by_name['SampleData'] = _SAMPLEDATA
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SampleData = _reflection.GeneratedProtocolMessageType('SampleData', (_message.Message,), {
  'DESCRIPTOR' : _SAMPLEDATA,
  '__module__' : 'sample_data_pb2'
  # @@protoc_insertion_point(class_scope:SampleData)
  })
_sym_db.RegisterMessage(SampleData)


# @@protoc_insertion_point(module_scope)
